Repository aws-controllers-k8s/code-generator, pull requests merged in 2021-08, with the labels that each got.

#140 Expose `SetSDKForStruct` and `SetResourceForStruct` in templates
  pkg/generate/ack/apis.go
  pkg/generate/ack/controller.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_sdk.go
Labels: approved, lgtm

#144 Add CORS to initialisms
  pkg/names/names.go
Labels: approved, lgtm

#145 Remove loops from GetWrapperOutputShape
  pkg/model/crd.go
Labels: approved, lgtm, ok-to-test

#143 aws-sdk-go version bump, 1.37.4 -> 1.37.10
  Makefile
  go.mod
  go.sum
Labels: approved, lgtm

#146 Generate typedefs for payload fields in `Spec` and `Status`
  pkg/model/crd.go
  pkg/model/model.go
  pkg/model/model_ec2_test.go
  pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Labels: approved, lgtm

#147 add DPD and IO to initialisms
  pkg/names/names.go
  pkg/names/names_test.go
Labels: approved, lgtm, ok-to-test

#151 Add `SetStatus` for resource
  templates/pkg/resource/resource.go.tpl
Labels: lgtm, approved

#152 Update to ACK Runtime `v0.9.2`
  Makefile
  go.mod
  go.sum
  pkg/generate/ack/runtime_test.go
Labels: lgtm, approved

#150 Minor Refactor in `pkg/generate/code`
  pkg/generate/code/check.go
  pkg/generate/code/common.go
  pkg/generate/code/common_test.go
  pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Labels: lgtm, approved, needs-ok-to-test

#153 Add operator-sdk and olm scripts to code-generator repo.
  scripts/install-operator-sdk.sh
  scripts/olm-build-bundle-image.sh
  scripts/olm-create-bundle.sh
  scripts/olm-publish-bundle-image.sh
Labels: lgtm, approved

#138 Initial implementation of AWSResourceManager.LateInitialize() method.
  Makefile
  go.mod
  go.sum
  pkg/generate/ack/controller.go
  pkg/generate/ack/hook.go
  pkg/generate/ack/runtime_test.go
  pkg/generate/code/late_initialize.go
  pkg/generate/code/late_initialize_test.go
  pkg/generate/config/field.go
  pkg/testdata/models/apis/ecr/0000-00-00/generator-with-field-config.yaml
  pkg/testdata/models/apis/ecr/0000-00-00/generator-with-late-initialize.yaml
  pkg/testdata/models/apis/ecr/0000-00-00/generator-with-nested-path-late-initialize.yaml
  templates/pkg/resource/manager.go.tpl
Labels: lgtm, approved

#154 Import Aws service package and pass EndpointsID to serviceController
  Makefile
  go.mod
  go.sum
  templates/cmd/controller/main.go.tpl
Labels: lgtm, approved, needs-ok-to-test

#157 use reflect to compare map/slice struct
  pkg/generate/code/compare.go
  pkg/generate/code/compare_test.go
  templates/pkg/resource/delta.go.tpl
Labels: lgtm, approved

#155 Implement ReadMany for CheckRequiredFieldsMissingFromShape
  pkg/generate/ack/controller.go
  pkg/generate/code/check.go
  pkg/generate/code/check_test.go
  pkg/generate/code/common.go
  templates/pkg/resource/sdk_find_read_many.go.tpl
Labels: lgtm, approved, needs-ok-to-test

#158 Update to ACK runtime `v0.12.0`
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved

#159 small helm template fixes
  templates/helm/templates/deployment.yaml
  templates/helm/values.yaml.tpl
Labels: lgtm, approved

#161 add vlan to initialisms
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved, ok-to-test

#162 Support default non-release version in build-controller-release.sh
  Makefile
  scripts/build-controller-release.sh
Labels: lgtm, approved

#164 use latest tag before non-release version
  scripts/build-controller-release.sh
Labels: lgtm, approved

#163 Allow override resource identifier to ARN
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/testdata/models/apis/sagemaker/0000-00-00/generator.yaml
Labels: enhancement, lgtm, approved

#156 Implement ReadMany operation for SetSDK generator function
  pkg/generate/code/set_sdk.go
  pkg/generate/code/set_sdk_test.go
  pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Labels: lgtm, approved, ok-to-test

#165 add ami to initialisms
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved, needs-ok-to-test

#167 update ami rule in initialisms
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved, ok-to-test

#172 Use `ServiceMetadata` strings in Helm charts
  cmd/ack-generate/command/release.go
  pkg/generate/ack/release.go
  pkg/metadata/service_metadata.go
  pkg/model/multiversion/manager.go
  templates/helm/Chart.yaml.tpl
Labels: lgtm, approved

#173 Prepend 'https://proxy.golang.org' to GOPROXY in Dockerfile for building controller image.
  Dockerfile
Labels: lgtm, approved

#166 Allow OperatorType to be a list such that one API can map to multiple operations
  pkg/generate/config/operation.go
  pkg/model/sdk_helper.go
Labels: lgtm, approved, ok-to-test

#176 visibility for AWS err code in addition to message
  templates/pkg/resource/sdk.go.tpl
Labels: lgtm, approved

#175 update conditions on error for delete operation
  templates/pkg/resource/manager.go.tpl
Labels: lgtm, approved
