Repository aws-controllers-k8s/code-generator, pull requests merged in 2021-11, with the labels that each got.

#235 making ack-user-config and ack-user-secrets required in the deployment template
  templates/config/controller/user-env.yaml.tpl
Labels: lgtm, approved, ok-to-test

#236 Prevent generated types from colliding with Resources
  templates/crossplane/apis/type_def.go.tpl
Labels: lgtm, approved, ok-to-test

#237 Use loadModelWithLatestAPIVersion to load models for crossplane
  cmd/ack-generate/command/crossplane.go
  cmd/ack-generate/command/root.go
  templates/crossplane/README.md
Labels: lgtm, approved, needs-ok-to-test

#241 Add Bryan Carter to OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved

#232 allow different Go types for input/output shapes
  pkg/generate/ack/controller.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/generate/config/field.go
  pkg/model/field.go
  pkg/model/op.go
  pkg/testdata/models/apis/apigatewayv2/0000-00-00/generator.yaml
  pkg/testdata/models/apis/elasticache/0000-00-00/generator.yaml
  pkg/testdata/models/apis/rds/0000-00-00/generator.yaml
Labels: lgtm, approved

#242 changing CSV template to use categories
  templates/config/manifests/bases/clusterserviceversion.yaml.tpl
Labels: lgtm, approved, ok-to-test

#244 Add `UUID` to initialism
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved

#243 Remove code setting a resource ARN from its spec primary identifier
  pkg/generate/code/set_sdk.go
Labels: lgtm, approved

#245 add NAT to initialisms
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved
