Repository aws-controllers-k8s/code-generator, pull requests merged in 2021-09, with the labels that each got.

#178 Add unit tests to common_test
  pkg/generate/code/common_test.go
Labels: lgtm, approved, ok-to-test

#177 Refactor `setSDKReadMany` and `setResourceForScalar`
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_sdk.go
Labels: lgtm, approved, ok-to-test

#180 Update base images to ECR public
  Dockerfile
  Dockerfile.local
  scripts/build-controller-image.sh
Labels: lgtm, approved

#181 aws-controllers-k8s/runtime update from v0.13.0 to v0.13.1
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved

#182 return nil if observed is nil from a successful delete
  templates/pkg/resource/manager.go.tpl
Labels: lgtm, approved

#183 Support nested paths in field config specifically list type members
  pkg/model/sdk_helper.go
  pkg/model/sdk_helper_test.go
Labels: lgtm, approved, ok-to-test

#184 Only return MetaObject from AWSResource.MetaObject() call
  templates/pkg/resource/resource.go.tpl
Labels: lgtm, approved

#186 Upgrade to ACK runtime v0.13.2
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved

#187 Fix installation of controller-gen in prowjobs
  scripts/install-controller-gen.sh
Labels: lgtm, approved

#188 Remove the last modification timestamp and the OS/Arch from `ack-generate-metadata.yaml` file.
  pkg/metadata/generation_metadata.go
Labels: lgtm, approved

#185 Added node selector for helm chart
  templates/helm/templates/deployment.yaml
  templates/helm/values.yaml.tpl
Labels: lgtm, approved, ok-to-test

#189 Optionally log into ECR public
  scripts/build-controller-image.sh
  scripts/lib/common.sh
Labels: lgtm, approved

#191 compare ptr using ==
  templates/pkg/resource/manager.go.tpl
Labels: lgtm, approved

#193 import ACK runtime pkg/condition in sdk.go
  templates/pkg/resource/sdk.go.tpl
Labels: lgtm, approved

#190 Replace `primary_identifier_field_name` with `is_primary_key`
  pkg/generate/code/common.go
  pkg/generate/code/set_resource.go
  pkg/generate/config/field.go
  pkg/generate/config/operation.go
  pkg/generate/config/resource.go
  pkg/model/crd.go
  pkg/testdata/models/apis/ecr/0000-00-00/generator-with-field-config.yaml
  pkg/testdata/models/apis/rds/0000-00-00/generator.yaml
  pkg/testdata/models/apis/sagemaker/0000-00-00/generator.yaml
Labels: approved

#194 Update to ACK runtime `v0.14.0`
  Makefile
  go.mod
  go.sum
Labels: approved

#195 Shorten metric service name
  templates/helm/templates/metrics-service.yaml
Labels: lgtm, approved

#196 Use docker expiration string from auth config
  scripts/lib/common.sh
Labels: lgtm, approved

#197 use return statement instead of exit in is_public_ecr_logged_in
  scripts/lib/common.sh
Labels: lgtm, approved

#200 adding back required `install-kustomize.sh` file
  scripts/install-kustomize.sh
Labels: lgtm, approved, needs-ok-to-test

#199 Doc link fix
  CONTRIBUTING.md
  scripts/build-controller.sh
Labels: approved

#203 updating containerImage format in clusterserviceversion
  pkg/generate/olm/olm.go
  templates/config/manifests/bases/clusterserviceversion.yaml.tpl
Labels: lgtm, approved, needs-ok-to-test

#202 Update to controller-gen `v0.7.0`
  pkg/generate/code/compare.go
  pkg/generate/code/compare_test.go
  scripts/lib/common.sh
Labels: lgtm, approved

#205 Update ACK runtime to v0.14.1
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved

#204 updating image format in olm create bundle to match the new image format
  scripts/olm-create-bundle.sh
Labels: lgtm, approved, ok-to-test

#206 fixing formatting in container image to be consistent with image
  pkg/generate/olm/olm.go
  templates/config/manifests/bases/clusterserviceversion.yaml.tpl
Labels: lgtm, approved, needs-ok-to-test

#207 Add invocation of olm-create-bundle.sh to build-controller-release.sh
  scripts/build-controller-release.sh
  scripts/olm-create-bundle.sh
Labels: lgtm, approved, needs-ok-to-test

#210 Reference `output_wrapper_field_path` when generating CRD fields as part of the `Create*` request in `model.go`
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/model/crd.go
  pkg/model/model.go
  pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Labels: lgtm, approved

#211 Allow separate service ID and alias
  cmd/ack-generate/command/apis.go
  cmd/ack-generate/command/controller.go
  cmd/ack-generate/command/crossplane.go
  cmd/ack-generate/command/olm.go
  cmd/ack-generate/command/release.go
  cmd/ack-generate/command/root.go
  pkg/generate/templateset/vars.go
  pkg/model/model.go
  pkg/model/multiversion/manager.go
  pkg/model/sdk_helper.go
  pkg/testutil/schema_helper.go
  scripts/build-controller-release.sh
  scripts/build-controller.sh
Labels: lgtm, approved
