Repository aws-controllers-k8s/code-generator, pull requests merged in 2021-06, with the labels that each got.

#74 Add missing `sdk_delete_post_build_request` hook in `sdk.go.tpl`
  templates/pkg/resource/sdk.go.tpl
Labels: approved, lgtm

#70 Immutable fields advisory
  pkg/generate/config/field.go
  pkg/model/crd.go
  templates/pkg/resource/sdk.go.tpl
  templates/pkg/resource/sdk_update.go.tpl
Labels: approved, lgtm

#31 crossplane: fix the controller template for attribute-based APIs
  templates/crossplane/pkg/controller.go.tpl
Labels: approved, lgtm

#77 Explicitly mentioning 'metrics' for the ACK controller service.
  templates/helm/templates/metrics-service.yaml
  templates/helm/values.yaml.tpl
Labels: approved, lgtm

#75 Update ElastiCache CodeGen test based on new SDK
  pkg/generate/code/set_resource_test.go
  pkg/generate/code/set_sdk_test.go
  pkg/generate/elasticache_test.go
  pkg/generate/testdata/models/apis/elasticache/0000-00-00/api-2.json
  pkg/generate/testdata/models/apis/elasticache/0000-00-00/docs-2.json
  pkg/generate/testdata/models/apis/elasticache/0000-00-00/generator.yaml
Labels: approved, lgtm

#79 Add a new config to override kubebuilder `printcolumn:name`
  pkg/generate/config/field.go
  pkg/model/printer_column.go
Labels: approved, lgtm

#80 Add metrics-service.yaml to helm template files.
  pkg/generate/ack/release.go
Labels: approved, lgtm

#81 crossplane: Mark spec as required, status.atProvider as optional
  templates/crossplane/apis/crd.go.tpl
Labels: approved, lgtm, ok-to-test

#76 Patch the correct observed state after a `rm.ReadOne` call
  templates/pkg/resource/manager.go.tpl
Labels: approved, lgtm

#85 crossplane: remove unnecessary error handling in Update
  templates/crossplane/pkg/controller.go.tpl
Labels: approved, lgtm, ok-to-test

#86 Add a new config to override `kubebuilder:printcolumn` priority
  pkg/generate/config/field.go
  pkg/model/printer_column.go
  templates/apis/crd.go.tpl
Labels: approved, lgtm

#87 Extend ack-generate to generate slice with elements of type K8s Secret
  pkg/generate/code/set_sdk.go
  pkg/generate/code/set_sdk_test.go
  pkg/generate/elasticache_test.go
  pkg/generate/testdata/models/apis/elasticache/0000-00-00/generator.yaml
  pkg/model/field.go
  pkg/model/types.go
Labels: approved, lgtm

#78 Add a new operation config to override the `SetOutput` wrapper field
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/generate/config/operation.go
  pkg/generate/testdata/models/apis/dynamodb/0000-00-00/generator.yaml
  pkg/model/crd.go
Labels: approved, lgtm

#89 Add base CRD documentation
  pkg/model/crd.go
  templates/apis/crd.go.tpl
Labels: approved, lgtm

#84 Add a new generator config to append an Age `printcolumn`
  pkg/generate/config/resource.go
  pkg/model/crd.go
  templates/apis/crd.go.tpl
Labels: approved, lgtm

#93 fix: use deterministic sort for identifier field
  pkg/model/crd.go
Labels: approved, lgtm

#96 Conditionally allow view secrets on ClusterRole
  Makefile
  pkg/generate/ack/controller.go
  pkg/generate/config/config.go
  pkg/generate/generator.go
  templates/pkg/resource/registry.go.tpl
Labels: approved, lgtm

#97 Support suffix exception
  pkg/generate/ack/controller.go
  pkg/generate/code/check.go
  pkg/generate/config/resource.go
  pkg/generate/crossplane/crossplane.go
  pkg/generate/sagemaker_test.go
  pkg/generate/testdata/models/apis/sagemaker/0000-00-00/generator.yaml
  templates/crossplane/pkg/conversions.go.tpl
  templates/pkg/resource/sdk_find_get_attributes.go.tpl
  templates/pkg/resource/sdk_find_read_many.go.tpl
  templates/pkg/resource/sdk_find_read_one.go.tpl
  templates/pkg/resource/sdk_update_set_attributes.go.tpl
Labels: approved, lgtm, needs-ok-to-test

#98 trace sdk.go resource manager methods
  go.mod
  go.sum
  pkg/generate/ack/runtime_test.go
  pkg/generate/mq_test.go
  pkg/model/crd.go
  templates/pkg/resource/manager.go.tpl
  templates/pkg/resource/sdk.go.tpl
  templates/pkg/resource/sdk_find_get_attributes.go.tpl
  templates/pkg/resource/sdk_find_read_many.go.tpl
  templates/pkg/resource/sdk_find_read_one.go.tpl
  templates/pkg/resource/sdk_update.go.tpl
Labels: approved, lgtm

#91 Enable crd variables and controller functions and hooks within hook templates
  pkg/generate/ack/controller.go
  pkg/generate/ack/hook.go
  pkg/generate/ack/hook_test.go
Labels: approved, lgtm, ok-to-test

#92 Add CRD method to get OutputShape
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/model/crd.go
Labels: approved, lgtm, ok-to-test

#100 fix template for create custom implementation scenario
  templates/pkg/resource/sdk.go.tpl
Labels: approved, lgtm

#101 prevent unused variable error
  templates/pkg/resource/sdk.go.tpl
  templates/pkg/resource/sdk_update.go.tpl
Labels: approved, lgtm

#102 Remove duplicate `aws-sdk-go/$service` import
  templates/pkg/resource/sdk.go.tpl
Labels: approved, lgtm

#104 Fix missing replace conditions method
  pkg/generate/mq_test.go
  pkg/model/crd.go
  templates/pkg/resource/resource.go.tpl
Labels: approved, lgtm

#106 align code-generator to ACK runtime v0.3.0
  go.mod
  go.sum
  pkg/generate/ack/runtime_test.go
Labels: approved

#95 Provide an option to configure a resource to requeue infinitely (Issue #826)
  pkg/generate/config/resource.go
  pkg/generate/sagemaker_test.go
  pkg/generate/testdata/models/apis/sagemaker/0000-00-00/generator.yaml
  pkg/model/crd.go
  templates/pkg/resource/manager.go.tpl
  templates/pkg/resource/manager_factory.go.tpl
  templates/pkg/resource/sdk.go.tpl
Labels: approved, lgtm, needs-ok-to-test

#107 Add OIDC and identity to initialisms
  pkg/names/names.go
Labels: approved, lgtm

#109 Copy `generator.yaml` to apis/version directory
  cmd/ack-generate/command/apis.go
  pkg/util/file.go
Labels: approved, lgtm

#110 Bump ack-generate `VERSION` variable
  Makefile
Labels: approved, lgtm

#108 Use `go-git` functionalities for common git operations
  ATTRIBUTION.md
  cmd/ack-generate/command/apis.go
  cmd/ack-generate/command/common.go
  cmd/ack-generate/command/controller.go
  cmd/ack-generate/command/crossplane.go
  cmd/ack-generate/command/olm.go
  cmd/ack-generate/command/release.go
  go.mod
  go.sum
  pkg/util/git.go
Labels: approved, lgtm
