Repository aws-controllers-k8s/code-generator, pull requests merged in 2021-12, with the labels that each got.

#248 introduce pkg/fieldpath for processing field paths
  pkg/fieldpath/path.go
  pkg/fieldpath/path_test.go
Labels: lgtm, approved

#249 Added scheduling parameters to helm template;
  templates/helm/templates/deployment.yaml
  templates/helm/values.yaml.tpl
Labels: lgtm, approved, ok-to-test

#250 allow iterating over a fieldpath's ShapeRefs
  pkg/fieldpath/path.go
  pkg/fieldpath/path_test.go
Labels: lgtm, approved

#251 fix(group): group redeclared issue fixed
  templates/crossplane/apis/crd.go.tpl
  templates/crossplane/apis/groupversion_info.go.tpl
Labels: lgtm, approved, ok-to-test

#252 Adds helm schema validation
  pkg/generate/ack/release.go
  templates/helm/values.schema.json
Labels: lgtm, approved, needs-ok-to-test

#253 Default priorityClassName to blank string
  templates/helm/values.yaml.tpl
Labels: lgtm, approved, needs-ok-to-test
