Repository aws-controllers-k8s/code-generator, pull requests merged in 2021-07, with the labels that each got.

#105 Generate resource identifiers from `ReadOne` or `ReadMany`
  pkg/generate/ack/controller.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/generate/config/operation.go
  pkg/generate/testdata/models/apis/rds/0000-00-00/generator.yaml
  pkg/model/crd.go
  templates/pkg/resource/resource.go.tpl
Labels: approved, lgtm

#113 Fix required fields for renamed ReadOne input
  pkg/generate/code/check.go
  pkg/generate/code/check_test.go
  pkg/generate/testdata/models/apis/eks/0000-00-00/api-2.json
  pkg/generate/testdata/models/apis/eks/0000-00-00/docs-2.json
  pkg/generate/testdata/models/apis/eks/0000-00-00/generator.yaml
Labels: approved, lgtm, ok-to-test

#111 Setup webhooks on controller startup
  templates/cmd/controller/main.go.tpl
Labels: approved

#115 Correct type mismatch errors in `SetResourceIdentifiers` generated code
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
Labels: approved, lgtm

#116 Add primary identifiers for `ReadMany` operations
  pkg/generate/code/set_resource.go
Labels: approved, lgtm

#117 handle renamed fields for resource identifiers
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
Labels: approved, lgtm

#118 pin code-gen to ACK runtime v0.4.0
  Makefile
  go.mod
  go.sum
  pkg/generate/ack/runtime_test.go
Labels: approved, lgtm

#112 Add new type to OperationConfig so user can implement CustomCheckRequiredFieldsMissingMethod
  pkg/generate/config/operation.go
  pkg/model/crd.go
  templates/pkg/resource/sdk_find_get_attributes.go.tpl
  templates/pkg/resource/sdk_find_read_one.go.tpl
  templates/pkg/resource/sdk_update_set_attributes.go.tpl
Labels: approved, lgtm, ok-to-test

#123 Graceful cancellation for network dependent commands
  cmd/ack-generate/command/apis.go
  cmd/ack-generate/command/common.go
  cmd/ack-generate/command/controller.go
  cmd/ack-generate/command/crossplane.go
  cmd/ack-generate/command/olm.go
  cmd/ack-generate/command/release.go
Labels: approved, lgtm

#124 Add a new sort option for `kubebuilder:printcolumns` marker comments
  pkg/generate/config/field.go
  pkg/model/printer_column.go
Labels: approved, lgtm

#125 Migrate image build and release scripts from `community`
  Dockerfile
  Dockerfile.local
  Makefile
  scripts/build-controller-image.sh
  scripts/build-controller-release.sh
Labels: approved

#114 Returning the latest resource from the Delete() call
  Makefile
  go.mod
  templates/pkg/resource/manager.go.tpl
  templates/pkg/resource/sdk.go.tpl
Labels: approved, lgtm

#121 Bring in `pkg/model/multiversion` package to help interacting with multiple API versions
  pkg/model/crd.go
  pkg/model/multiversion/api_info.go
  pkg/model/multiversion/delta.go
  pkg/model/multiversion/delta_renames.go
  pkg/model/multiversion/delta_renames_test.go
  pkg/model/multiversion/delta_test.go
  pkg/model/multiversion/manager.go
  pkg/model/sdk_helper.go
  pkg/testdata/models/apis/ecr/0000-00-00/generator-v1alpha1.yaml
  pkg/testdata/models/apis/ecr/0000-00-00/generator-v1alpha2.yaml
  pkg/testdata/models/apis/ecr/0000-00-00/generator-v1alpha3.yaml
  pkg/testdata/models/apis/ecr/0000-00-01/api-2.json
  pkg/testdata/models/apis/ecr/0000-00-01/docs.json
  pkg/testdata/models/apis/ecr/0000-00-01/generator-v1beta1.yaml
  pkg/testdata/models/apis/ecr/0000-00-01/generator-v1beta2.yaml
  pkg/testutil/schema_helper.go
Labels: approved, do-not-merge/hold, lgtm

#127 Recursively build a clean GoType for nested maps and arrays
  pkg/model/model.go
Labels: approved, lgtm

#126 Add service metadata configuration file
  cmd/ack-generate/command/apis.go
  cmd/ack-generate/command/root.go
  go.sum
  pkg/metadata/api_info.go
  pkg/metadata/generation_metadata.go
  pkg/metadata/service_metadata.go
  pkg/model/multiversion/manager.go
  pkg/testdata/models/metadata.yaml
  scripts/build-controller.sh
  scripts/construct-metadata.sh
  scripts/lib/metadata.sh
  templates/metadata.yaml
Labels: approved, lgtm

#128 pin code-gen to ACK runtime 0.6.0
  Makefile
  go.mod
  go.sum
  pkg/generate/ack/runtime_test.go
Labels: approved, lgtm

#94 Add sdk addon hook
  pkg/generate/ack/hook.go
  templates/pkg/resource/sdk.go.tpl
Labels: approved, lgtm

#129 Mark status fields as optional
  templates/apis/crd.go.tpl
Labels: approved, lgtm

#130 Add script and Github workflow for ensuring version in sync
  .github/workflows/version-check.yaml
  Makefile
  scripts/check-versions.sh
Labels: approved, lgtm

#131 Secret errors to be terminal code
  Makefile
  go.mod
  go.sum
  pkg/generate/ack/runtime_test.go
  pkg/generate/code/set_sdk.go
  pkg/generate/config/resource.go
  templates/pkg/resource/sdk.go.tpl
Labels: approved, lgtm, needs-ok-to-test

#133 Add AWS_ENDPOINT_URL to Helm chart templates
  templates/helm/templates/deployment.yaml
  templates/helm/values.yaml.tpl
Labels: approved, lgtm, needs-ok-to-test

#132 Remove performSpecUpdate(boolean) from Set<Operation>Output.
  pkg/generate/ack/controller.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/generate/crossplane/crossplane.go
  templates/crossplane/pkg/controller.go.tpl
  templates/crossplane/pkg/sdk_find_read_many.go.tpl
  templates/crossplane/pkg/sdk_find_read_one.go.tpl
  templates/pkg/resource/sdk.go.tpl
  templates/pkg/resource/sdk_find_read_many.go.tpl
  templates/pkg/resource/sdk_find_read_one.go.tpl
  templates/pkg/resource/sdk_update.go.tpl
Labels: approved, lgtm

#134 Load metadata in release script
  scripts/build-controller-release.sh
Labels: approved, lgtm

#136 Update for helm charts to use latest ecr-public repository.
  cmd/ack-generate/command/release.go
  scripts/build-controller-release.sh
  templates/helm/Chart.yaml.tpl
  templates/helm/values.yaml.tpl
Labels: approved, lgtm

#135 Update required controller-gen to `v0.6.1`
  scripts/build-controller-release.sh
  scripts/build-controller.sh
  scripts/install-controller-gen.sh
  scripts/lib/common.sh
  scripts/lib/k8s.sh
Labels: approved, lgtm

#137 Default `AWS_SDK_GO_VERSION` to go.mod version
  scripts/build-controller-release.sh
  scripts/build-controller.sh
Labels: approved, lgtm

#139 Allow member fields from other operations in spec
  pkg/generate/code/compare_test.go
  pkg/model/crd.go
  pkg/model/model_s3_test.go
  pkg/testdata/models/apis/s3/0000-00-00/generator.yaml
Labels: approved, lgtm

#141 release script and helm bug fixes
  pkg/generate/ack/release.go
  scripts/build-controller-release.sh
  templates/helm/templates/cluster-role-binding.yaml
  templates/helm/templates/cluster-role-binding.yaml.tpl
Labels: approved, lgtm

#142 bring in ACK runtime v0.8.0
  Makefile
  go.mod
  go.sum
  pkg/generate/ack/runtime_test.go
  templates/pkg/resource/descriptor.go.tpl
Labels: approved, lgtm
