Repository aws-controllers-k8s/code-generator, pull requests merged in 2021-05, with the labels that each got.

#64 Add OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: do-not-merge/invalid-owners-file

#60 Namespace scope service controllers
  go.mod
  templates/cmd/controller/main.go.tpl
  templates/config/controller/deployment.yaml.tpl
  templates/helm/templates/deployment.yaml
  templates/helm/values.yaml.tpl
Labels: approved

#66 Panic if input field renames are not part of a resource spec/status fields
  pkg/generate/code/set_resource.go
Labels: approved

#67 panic if matchFieldName config contains an element that is not part of Spec or Status fields
  pkg/generate/code/set_resource.go
Labels: approved

#65 Add code generation for type comparison
  pkg/generate/ack/controller.go
  pkg/generate/code/equal.go
  pkg/generate/code/equal_test.go
  templates/pkg/compare/struct.go.tpl
Labels: approved, lgtm

#69 helm chart: add log and accountid
  go.mod
  go.sum
  templates/helm/templates/deployment.yaml
  templates/helm/values.yaml.tpl
Labels: approved, enhancement, lgtm

#71 Revert "Add code generation for type comparison"
  pkg/generate/ack/controller.go
  pkg/generate/code/equal.go
  pkg/generate/code/equal_test.go
  templates/pkg/compare/struct.go.tpl
Labels: approved, lgtm

#72 Add pre/post compare hooks for `newResourceDelta` function
  pkg/generate/ack/hook.go
  templates/pkg/resource/delta.go.tpl
Labels: approved, lgtm

#73 Adding ClusterIP service in helm chart to expose controller metrics.
  pkg/generate/ack/release.go
  templates/helm/templates/service.yaml
  templates/helm/values.yaml.tpl
Labels: approved, lgtm
