Repository aws-controllers-k8s/code-generator, pull requests merged in 2022-07, with the labels that each got.

#353 making user-secret in user-env optional to support IRSA
  templates/config/controller/user-env.yaml.tpl
Labels: lgtm, approved, needs-ok-to-test

#355 Refactor reusable code to ensure `aws-sdk-go` repository
  cmd/ack-generate/command/apis.go
  cmd/ack-generate/command/common.go
  cmd/ack-generate/command/controller.go
  cmd/ack-generate/command/crossplane.go
  cmd/ack-generate/command/olm.go
  cmd/ack-generate/command/release.go
  pkg/sdk/repo.go
Labels: lgtm, approved

#356 upgrade ACK runtime to v0.19.3
  go.mod
  go.sum
Labels: approved

#357 Remove faulty suffix trim from Helm deployment
  templates/helm/templates/deployment.yaml
Labels: lgtm, approved
