Repository aws-controllers-k8s/code-generator, pull requests merged in 2022-05, with the labels that each got.

#322 Add initialisms contained within ACM PCA
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved

#330 Add SRIOV and RAM to initialisms
  pkg/generate/code/set_sdk_test.go
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved

#331 update RAM initialism
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved

#311 add ServicePackageName to ack-user-config and ack-user secrets
  templates/config/controller/user-env.yaml.tpl
Labels: lgtm, approved, ok-to-test

#332 Add support for references within lists of structs
  pkg/generate/ack/controller.go
  pkg/generate/code/resource_reference.go
  pkg/generate/code/resource_reference_test.go
  pkg/model/crd.go
  pkg/model/model.go
  pkg/model/model_ec2_test.go
  pkg/testdata/models/apis/ec2/0000-00-00/generator-with-nested-reference.yaml
  templates/pkg/resource/references.go.tpl
Labels: lgtm, approved

#334 updating to the latest version of operator sdk
  scripts/install-operator-sdk.sh
Labels: lgtm, approved, needs-ok-to-test

#333 Align EC2 testdata models with `go.mod`
  pkg/generate/code/resource_reference_test.go
  pkg/generate/code/set_resource_test.go
  pkg/generate/code/set_sdk_test.go
  pkg/model/model_ec2_test.go
  pkg/testdata/models/apis/ec2/0000-00-00/api-2.json
  pkg/testdata/models/apis/ec2/0000-00-00/docs-2.json
  pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Labels: lgtm, approved

#336 Add SQS to initialisms
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved

#337 Support 'list' type in `output_wrapper_field_path`
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/model/crd.go
  pkg/model/model_ec2_test.go
  pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
Labels: lgtm, approved

#338 Crossplane's provider-aws has moved to the crossplane-contrib org
  templates/crossplane/README.md
  templates/crossplane/pkg/controller.go.tpl
  templates/crossplane/pkg/conversions.go.tpl
Labels: lgtm, approved, needs-ok-to-test
