Repository aws-controllers-k8s/code-generator, pull requests merged in 2023-03, with the labels that each got.

#424 use `Operation.ExportedName` not `Operation.Name`
  pkg/config/operation.go
  pkg/config/resource.go
  pkg/generate/code/common.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_sdk.go
  pkg/model/crd.go
  templates/pkg/resource/sdk.go.tpl
Labels: lgtm, approved, ok-to-test

#421 Add `404: ResourceError` handling in sdkFind
  templates/pkg/resource/sdk_find_read_one.go.tpl
Labels: lgtm, approved

#420 kustomize: use 'resources' instead of deprecated 'bases'
  scripts/olm-create-bundle.sh
  templates/config/crd/kustomization.yaml.tpl
  templates/config/default/kustomization.yaml.tpl
Labels: approved, ok-to-test

#425 Pin `k8s.io/apimachinery` to `v0.26.1` and`sigs.k8s.io/controller-runtime` to `v0.14.5`
  go.mod
  go.sum
Labels: approved

#426 Pin ACK runtime to `v0.24.1`
  go.mod
  go.sum
Labels: approved

#427 chore: Update Go deps
  go.mod
  go.sum
Labels: lgtm, approved

#394 support field custom documentation strings
  pkg/config/field.go
  pkg/model/field.go
  pkg/model/field_test.go
  pkg/testdata/models/apis/ec2/0000-00-00/generator-with-doc-overrides.yaml
  templates/apis/crd.go.tpl
Labels: lgtm, approved, ok-to-test

#422 Allow manual setting of AWS client struct and interface names
  cmd/ack-generate/command/common.go
  pkg/config/config.go
  pkg/generate/templateset/vars.go
  pkg/model/model.go
  pkg/model/sdk_api.go
  templates/crossplane/pkg/controller.go.tpl
  templates/pkg/resource/manager.go.tpl
  templates/pkg/resource/sdk.go.tpl
Labels: lgtm, approved

#428 QIL improvement to common.sh: check for null return status from ECR call
  scripts/lib/common.sh
Labels: lgtm, approved

#430 Remove optGenVersion from api path for goimports
  cmd/ack-generate/command/crossplane.go
Labels: lgtm, approved, ok-to-test

#431 Replace `GroupKind` with `GroupVersionKind` in `ResourceDescriptor`
  templates/pkg/resource/descriptor.go.tpl
Labels: approved

#433 Fix mocks for upcoming `AWSResourceDescriptor` changes
  pkg/generate/ack/runtime_test.go
Labels: approved

#432 Pin ACK runtime to `v0.25.0`
  go.mod
  go.sum
Labels: approved

#434 Inject missing code hook points in set attributes
  templates/pkg/resource/sdk_update_set_attributes.go.tpl
Labels: lgtm, approved
