Repository aws-controllers-k8s/code-generator, pull requests merged in 2023-12, with the labels that each got.

#475 Enhance resource comparison for collections and blobs
  pkg/generate/code/compare.go
  pkg/generate/code/compare_test.go
Labels: lgtm, approved

#478 Pin ACK runtime to `v0.28.0`
  go.mod
  go.sum
Labels: lgtm, approved

#454 Add `custom find_operation` support
  pkg/config/resource.go
  pkg/generate/ack/controller.go
  pkg/generate/code/set_resource.go
  pkg/model/crd.go
  templates/pkg/resource/sdk.go.tpl
  templates/pkg/resource/sdk_find_custom.go.tpl
Labels: lgtm, approved, ok-to-test

#461 chore: Support multi-arch containers build
  Dockerfile
  Dockerfile.local
  templates/config/manifests/bases/clusterserviceversion.yaml.tpl
Labels: lgtm, approved, ok-to-test

#480 Bump build image version
  Dockerfile
  Dockerfile.local
Labels: approved

#481 Default `AWS_SDK_GO_VERSION` to the last used version for code-generation
  scripts/build-controller.sh
Labels: approved
