Repository aws-controllers-k8s/code-generator, pull requests merged in 2023-05, with the labels that each got.

#423 Pass registered resource names to `config.Validate`
  templates/cmd/controller/main.go.tpl
Labels: lgtm, approved

#440 Update template to support watch namespace
  templates/helm/templates/_helpers.tpl
  templates/helm/values.schema.json
  templates/helm/values.yaml.tpl
Labels: lgtm, approved, ok-to-test

#444 chore: Fix spelling errors
  .codespellrc
  ATTRIBUTION.md
  pkg/config/resource.go
  pkg/generate/code/compare.go
  pkg/metadata/generation_metadata.go
  pkg/model/model_apigwv2_test.go
  pkg/model/multiversion/delta.go
  pkg/model/multiversion/delta_renames_test.go
  pkg/model/multiversion/manager.go
  pkg/model/op_test.go
  pkg/model/sdk_api.go
  pkg/testdata/models/apis/codedeploy/0000-00-00/api-2.json
  pkg/testdata/models/apis/codedeploy/0000-00-00/docs-2.json
  pkg/testdata/models/apis/dynamodb/0000-00-00/generator.yaml
  pkg/testdata/models/apis/ec2/0000-00-00/docs-2.json
  pkg/testdata/models/apis/ec2/0000-00-00/generator.yaml
  pkg/testdata/models/apis/ecr/0000-00-01/docs.json
  pkg/testdata/models/apis/elasticache/0000-00-00/docs-2.json
  pkg/testdata/models/apis/eventbridge/0000-00-00/docs-2.json
  pkg/testdata/models/apis/lambda/0000-00-00/docs-2.json
  pkg/testdata/models/apis/memorydb/0000-00-00/docs-2.json
  pkg/testdata/models/apis/rds/0000-00-00/docs-2.json
  pkg/testdata/models/apis/sagemaker/0000-00-00/docs-2.json
  pkg/testdata/models/apis/sns/0000-00-00/docs-2.json
  pkg/util/git.go
  scripts/build-controller-release.sh
  scripts/build-controller.sh
  scripts/olm-build-bundle-image.sh
  scripts/olm-publish-bundle-image.sh
  templates/pkg/resource/resource.go.tpl
Labels: lgtm, approved, needs-ok-to-test

#446 Add Seccomp profile to deployment
  templates/config/controller/deployment.yaml.tpl
  templates/helm/templates/deployment.yaml
  templates/helm/values.yaml.tpl
Labels: lgtm, approved, needs-ok-to-test

#441 Add new `$field.set[].To` configuration
  pkg/config/field.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_sdk.go
  pkg/generate/code/set_sdk_test.go
  pkg/model/crd.go
  pkg/testdata/models/apis/iam/0000-00-00/generator-user-newpath.yaml
Labels: lgtm, approved

#442 only call SetAttributes() when attrMap not empty
  pkg/generate/code/set_sdk.go
  pkg/generate/code/set_sdk_test.go
Labels: lgtm, approved

#445 Trim possible `v` prefixes in release code
  pkg/generate/ack/release.go
  pkg/generate/olm/olm.go
Labels: lgtm, approved

#448 updating operator-sdk to 1.28.0
  scripts/install-operator-sdk.sh
Labels: lgtm, approved, needs-ok-to-test

#449 Add Helm overrides for env vars, volumes and volume mounts
  templates/helm/templates/deployment.yaml
  templates/helm/values.schema.json
  templates/helm/values.yaml.tpl
Labels: lgtm, approved

#447 Create separate `documentation.yaml` file
  cmd/ack-generate/command/common.go
  cmd/ack-generate/command/root.go
  pkg/config/documentation.go
  pkg/config/field.go
  pkg/metadata/api_info.go
  pkg/model/crd.go
  pkg/model/field.go
  pkg/model/field_test.go
  pkg/model/model.go
  pkg/model/multiversion/manager.go
  pkg/testdata/models/apis/ec2/0000-00-00/generator-with-doc-overrides.yaml
  pkg/testdata/models/apis/eks/0000-00-00/documentation.yaml
  pkg/testutil/schema_helper.go
  scripts/build-controller-release.sh
  scripts/build-controller.sh
Labels: lgtm, approved
