Repository aws-controllers-k8s/code-generator, pull requests merged in 2023-04, with the labels that each got.

#437 Update runtime to `v0.26.0`
  go.mod
  go.sum
Labels: approved

#435 Support lists of structs containing refs and `ClearResolvedReferences`
  pkg/generate/ack/controller.go
  pkg/generate/ack/runtime_test.go
  pkg/generate/code/resource_reference.go
  pkg/generate/code/resource_reference_test.go
  pkg/model/model_ec2_test.go
  pkg/testdata/models/apis/ec2/0000-00-00/generator-with-nested-references.yaml
  pkg/testdata/models/apis/s3/0000-00-00/generator-with-nested-references.yaml
  pkg/testutil/schema_helper.go
  templates/pkg/resource/references.go.tpl
Labels: lgtm, approved

#438 Add OCI labels to docker images
  Dockerfile
  Dockerfile.local
Labels: lgtm, approved, ok-to-test

#439 Set Resource when GetAttribute is present
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/testdata/models/apis/sns/0000-00-00/generator.yaml
  pkg/testdata/models/apis/sqs/0000-00-00/generator.yaml
Labels: lgtm, approved, ok-to-test
