Repository aws-controllers-k8s/code-generator, pull requests merged in 2023-01, with the labels that each got.

#388 Add Helm support for the `--deletion-policy` CLI arg
  go.mod
  go.sum
  templates/helm/templates/deployment.yaml
  templates/helm/values.schema.json
  templates/helm/values.yaml.tpl
Labels: lgtm, approved

#389 Correct IdempotencyToken and OID initialism errors
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved, needs-ok-to-test

#366 Import `names` package from `github.com/aws-controllers-k8s/pkg`
  go.mod
  go.sum
  pkg/generate/code/compare.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_sdk.go
  pkg/model/attr.go
  pkg/model/crd.go
  pkg/model/enum_def.go
  pkg/model/field.go
  pkg/model/field_test.go
  pkg/model/model.go
  pkg/model/sdk_api.go
  pkg/model/type_def.go
  pkg/model/types.go
  pkg/names/names.go
  pkg/names/names_test.go
Labels: lgtm, approved

#387 Allow calling `GoCodeSetResourceForStruct` for non-CRD SDK shapes
  pkg/generate/ack/controller.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
  pkg/testdata/models/apis/eventbridge/0000-00-00/api-2.json
  pkg/testdata/models/apis/eventbridge/0000-00-00/docs-2.json
  pkg/testdata/models/apis/eventbridge/0000-00-00/generator.yaml
Labels: kind/enhancement, lgtm, approved

#372 Return a terminal error when `sdkUpdate` is not implemented
  templates/pkg/resource/sdk_update_not_implemented.go.tpl
Labels: lgtm, approved

#390 add: specific selector for operator
  templates/config/controller/deployment.yaml.tpl
  templates/config/controller/service.yaml.tpl
  templates/helm/templates/deployment.yaml
  templates/helm/templates/metrics-service.yaml
Labels: lgtm, approved, ok-to-test

#393 fix required fields that are renamed
  pkg/config/resource.go
  pkg/model/field.go
Labels: lgtm, approved, needs-ok-to-test

#395 Add error message for cloning sdk timeout
  pkg/sdk/repo.go
Labels: lgtm, approved, ok-to-test

#392 Lint all scripts with shellcheck
  Makefile
  scripts/build-controller-image.sh
  scripts/build-controller-release.sh
  scripts/build-controller.sh
  scripts/construct-metadata.sh
  scripts/install-controller-gen.sh
  scripts/install-helm.sh
  scripts/install-kustomize.sh
  scripts/install-operator-sdk.sh
  scripts/lib/aws.sh
  scripts/lib/common.sh
  scripts/lib/metadata.sh
  scripts/olm-build-bundle-image.sh
  scripts/olm-create-bundle.sh
  scripts/olm-publish-bundle-image.sh
Labels: lgtm, approved

#391 Add multi-arch and automatic Go version build support
  Dockerfile
  Dockerfile.local
  go.local.mod
  go.mod
  scripts/build-controller-image.sh
Labels: lgtm, approved
