Repository aws-controllers-k8s/code-generator, pull requests merged in 2023-02, with the labels that each got.

#397 Use `go env GOARCH` instead of `uname -i`
  scripts/build-controller-image.sh
Labels: lgtm, approved

#398 Revert "Correct the generated code for nested parent field reference."
  templates/pkg/resource/references.go.tpl
Labels: lgtm, approved

#400 Upgrade `aws-controllers-k8s/pkg` version
  go.mod
  go.sum
  pkg/generate/code/set_resource_test.go
Labels: lgtm, approved

#402 fix: Make CRD Synced Column type string
  templates/apis/crd.go.tpl
Labels: lgtm, approved

#403 Pin `ack/pkg` to `v0.0.1`
  go.mod
  go.sum
  pkg/generate/code/set_resource_test.go
Labels: lgtm, approved

#386 Complete support for resource-specific resync periods and default drift remediation period
  templates/config/controller/deployment.yaml.tpl
  templates/helm/templates/deployment.yaml
  templates/helm/values.schema.json
  templates/helm/values.yaml.tpl
Labels: lgtm, approved

#407 gofmt 1.20 updates (style-only changes)
  pkg/config/config.go
  pkg/config/field.go
  pkg/fieldpath/path.go
  pkg/generate/code/check.go
  pkg/generate/code/compare.go
  pkg/generate/code/initialize_field.go
  pkg/generate/code/late_initialize.go
  pkg/generate/code/resource_reference.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_sdk.go
  pkg/generate/code/synced.go
  pkg/model/multiversion/delta.go
  pkg/model/multiversion/delta_renames.go
  pkg/model/types.go
Labels: lgtm, approved, needs-ok-to-test

#408 bring in pkg@v0.0.3
  go.mod
  go.sum
  pkg/generate/code/set_resource_test.go
  pkg/generate/code/set_sdk_test.go
  pkg/model/model_sqs_test.go
Labels: lgtm, approved, ok-to-test

#401 Refactor reference resolution into Go code
  go.mod
  go.sum
  pkg/generate/ack/controller.go
  pkg/generate/code/resource_reference.go
  pkg/generate/code/resource_reference_test.go
  pkg/testdata/models/apis/s3/0000-00-00/generator-with-nested-references.yaml
  templates/pkg/resource/references.go.tpl
  templates/pkg/resource/references_read_referenced_resource.go.tpl
Labels: lgtm, approved

#399 Compare tags using common tag type
  pkg/generate/code/compare.go
  pkg/generate/code/compare_test.go
  pkg/model/model_s3_test.go
  pkg/testdata/models/apis/lambda/0000-00-00/generator.yaml
  pkg/testdata/models/apis/s3/0000-00-00/generator.yaml
  templates/pkg/resource/delta.go.tpl
Labels: lgtm, approved

#405 Deterministic result order in `GetImmutableFieldPaths`
  pkg/model/crd.go
Labels: lgtm, approved

#410 Fix default value of `--reconcile-resource` flag in deployment.yaml
  templates/config/controller/deployment.yaml.tpl
Labels: approved

#411 Remove all the `--reconcile-*` flags
  templates/config/controller/deployment.yaml.tpl
Labels: lgtm, approved

#412 Correct number of parameters to `GoCodeResolveReference`
  templates/pkg/resource/references.go.tpl
Labels: lgtm, approved

#414 Revert resource reference resolution
  pkg/generate/ack/controller.go
  pkg/generate/code/resource_reference.go
  pkg/generate/code/resource_reference_test.go
  pkg/testdata/models/apis/s3/0000-00-00/generator-with-nested-references.yaml
  templates/pkg/resource/references.go.tpl
  templates/pkg/resource/references_read_referenced_resource.go.tpl
Labels: lgtm, approved

#415 check for nil Name field in attr APIs
  pkg/generate/code/set_sdk.go
Labels: approved, ok-to-test

#417 Refactor reference resolution into Go code
  pkg/generate/ack/controller.go
  pkg/generate/code/resource_reference.go
  pkg/generate/code/resource_reference_test.go
  pkg/testdata/models/apis/iam/0000-00-00/generator.yaml
  pkg/testdata/models/apis/s3/0000-00-00/generator-with-nested-references.yaml
  templates/pkg/resource/references.go.tpl
  templates/pkg/resource/references_read_referenced_resource.go.tpl
Labels: approved

#406 Add `OmitUnchangedField` config for selective inclusion of changed `CRD` fields in update requests.
  pkg/config/resource.go
  pkg/generate/code/set_sdk.go
  pkg/generate/code/set_sdk_test.go
  pkg/model/crd.go
  pkg/testdata/models/apis/mq/0000-00-00/generator.yaml
  templates/pkg/resource/sdk_update.go.tpl
Labels: lgtm, approved
