Repository aws-controllers-k8s/code-generator, pull requests merged in 2024-01, with the labels that each got.

#484 Default `AWS_SDK_GO_VERSION` to the last used version in release script
  scripts/build-controller-release.sh
Labels: approved

#485 Introducing a generator configuration for GoTag customization
  pkg/config/field.go
  pkg/model/field.go
  pkg/model/field_test.go
  pkg/testdata/models/apis/eks/0000-00-00/generator-with-gotag.yaml
  templates/apis/crd.go.tpl
Labels: lgtm, approved

#486 Add ability to set custom `sdkDelete` functions
  pkg/config/resource.go
  pkg/generate/ack/controller.go
  pkg/model/crd.go
  templates/pkg/resource/sdk.go.tpl
  templates/pkg/resource/sdk_delete_custom.go.tpl
Labels: lgtm, approved

#487 Extend GoTag configuration to nested fields and attributes
  pkg/model/attr.go
  pkg/model/model.go
  templates/apis/type_def.go.tpl
Labels: lgtm, approved

#488 Add support for injecting custom fields of type `bytes`
  pkg/model/sdk_api.go
Labels: lgtm, approved

#489 Remove redundant new lines in `sdk.go` and `role-writer` templates
  templates/helm/templates/role-writer.yaml.tpl
  templates/pkg/resource/sdk.go.tpl
Labels: lgtm, approved

#483 Add support for Multi Namespace watch mode
  go.mod
  go.sum
  pkg/generate/olm/olm.go
  templates/cmd/controller/main.go.tpl
  templates/helm/values.yaml.tpl
Labels: approved

#492 Safely assign resources to the sdk opType maps
  pkg/model/sdk_api.go
Labels: lgtm, approved

#493 Correctly handle watchNamespace flag parsing errors
  templates/cmd/controller/main.go.tpl
Labels: lgtm, approved

#496 Security update: Migrate to `go-git/go-git` v5
  go.mod
  go.sum
  pkg/model/multiversion/manager.go
  pkg/sdk/helper.go
  pkg/util/git.go
Labels: lgtm, approved, area/security

#495 Enhance controller RBAC and helm charts generation
  pkg/generate/ack/release.go
  scripts/build-controller-release.sh
  templates/helm/templates/_controller-role-kind-patch.yaml.tpl
  templates/helm/templates/_helpers.tpl
  templates/helm/templates/caches-role-binding.yaml.tpl
  templates/helm/templates/caches-role.yaml.tpl
  templates/helm/templates/cluster-role-binding.yaml.tpl
  templates/helm/templates/cluster-role-controller.yaml.tpl
Labels: lgtm, approved

#498 Security update: Bump some core dependencies
  go.mod
  go.sum
Labels: lgtm, approved

#499 Bump controller-gen minimum version to v0.14.0
  scripts/lib/common.sh
Labels: lgtm, approved
