Repository aws-controllers-k8s/code-generator, pull requests merged in 2024-02, with the labels that each got.

#500 Adapt release generator to controller-gen 0.14.0 new format
  scripts/build-controller-release.sh
Labels: lgtm, approved

#501 Default watchNamespace to release namespace
  templates/helm/templates/cluster-role-binding.yaml.tpl
  templates/helm/templates/cluster-role-controller.yaml.tpl
Labels: lgtm, approved

#502 Pin `github.com/aws-controllers-k8s/pkg` to v0.0.8
  go.mod
  go.sum
Labels: lgtm, approved

#503 Pin `github.com/aws-controllers-k8s/pkg` to v0.0.9
  go.mod
  go.sum
Labels: lgtm, approved

#504 Resolve conflicts in helm templates/values
  pkg/generate/ack/release.go
  templates/helm/templates/_helpers.tpl
  templates/helm/templates/_helpers.tpl.tpl
  templates/helm/templates/cluster-role-binding.yaml.tpl
  templates/helm/templates/cluster-role-controller.yaml.tpl
  templates/helm/templates/deployment.yaml
  templates/helm/templates/deployment.yaml.tpl
  templates/helm/templates/leader-election-role-binding.yaml.tpl
  templates/helm/templates/metrics-service.yaml
  templates/helm/templates/metrics-service.yaml.tpl
  templates/helm/templates/service-account.yaml
  templates/helm/templates/service-account.yaml.tpl
Labels: lgtm, approved

#505 Pin `github.com/aws-controllers/runtime` to v0.30.0
  go.mod
  go.sum
Labels: lgtm, approved

#494 Experimental configurations to override controller names
  cmd/ack-generate/command/common.go
  cmd/ack-generate/command/controller.go
  pkg/config/config.go
  pkg/generate/ack/release.go
  pkg/generate/templateset/vars.go
  pkg/model/model.go
  templates/cmd/controller/main.go.tpl
  templates/config/controller/deployment.yaml.tpl
  templates/config/controller/olm-kustomization.yaml.tpl
  templates/config/controller/service.yaml.tpl
  templates/config/controller/user-env.yaml.tpl
  templates/config/manifests/bases/clusterserviceversion.yaml.tpl
  templates/config/overlays/namespaced/kustomization.yaml.tpl
  templates/config/rbac/cluster-role-binding.yaml.tpl
  templates/config/rbac/leader-election-role-binding.yaml.tpl
  templates/config/rbac/leader-election-role.yaml.tpl
  templates/config/rbac/role-reader.yaml.tpl
  templates/config/rbac/role-writer.yaml.tpl
  templates/helm/Chart.yaml.tpl
  templates/helm/templates/caches-role-binding.yaml.tpl
  templates/helm/templates/caches-role.yaml.tpl
  templates/helm/templates/cluster-role-binding.yaml.tpl
  templates/helm/templates/cluster-role-controller.yaml.tpl
  templates/helm/templates/leader-election-role-binding.yaml.tpl
  templates/helm/templates/leader-election-role.yaml.tpl
  templates/helm/templates/role-reader.yaml.tpl
  templates/helm/templates/role-writer.yaml.tpl
  templates/helm/values.yaml.tpl
  templates/pkg/resource/descriptor.go.tpl
  templates/pkg/resource/manager.go.tpl
  templates/pkg/resource/manager_factory.go.tpl
  templates/pkg/resource/references.go.tpl
  templates/pkg/resource/resource.go.tpl
  templates/pkg/resource/sdk.go.tpl
  templates/pkg/resource/tags.go.tpl
Labels: lgtm, approved

#506 update OLM's manifest/bases/csv generation to use `ControllerName`
  pkg/generate/olm/olm.go
Labels: lgtm, approved, ok-to-test

#507 updating release script logic for olm flow to use cache director
  scripts/build-controller-release.sh
Labels: lgtm, approved, ok-to-test

#509 Simplify controllers local build system
  Dockerfile.local
  Makefile
  go.local.mod
  go.local.sum
  scripts/build-controller-image.sh
Labels: lgtm, approved

#510 [local builds] move instructions to copy code before go mod commands
  Dockerfile.local
Labels: approved

#511 [runtime builds] Include mocks and run `go mod tidy` before builds
  Dockerfile.local
Labels: approved

#508 Configure liveness and readiness probes for controller deployments
  go.mod
  go.sum
  templates/cmd/controller/main.go.tpl
  templates/config/controller/deployment.yaml.tpl
  templates/helm/templates/deployment.yaml.tpl
Labels: lgtm, approved

#513 Pin `github.com/aws-controllers-k8s/pkg` to v0.0.10
  go.mod
  go.sum
Labels: lgtm, approved

#512 Extend `getAttributeFromPath` search to status fields as well.
  pkg/model/model.go
Labels: lgtm, approved

#514 Pin ACK runtime to `v0.31.0`
  go.mod
  go.sum
Labels: lgtm, approved
