Repository aws-controllers-k8s/code-generator, pull requests merged in 2025-02, with the labels that each got.

#567 Pin ACK runtime to v0.42.0
  go.mod
  go.sum
Labels: lgtm, approved

#568 Generate FilterSystemTags and mirrorAWSTags in controllers
  templates/pkg/resource/manager.go.tpl
  templates/pkg/resource/tags.go.tpl
Labels: lgtm, approved

#569 Pin ACK runtime to v0.43.0
  go.mod
  go.sum
  pkg/generate/ack/runtime_test.go
  templates/pkg/resource/manager.go.tpl
  templates/pkg/resource/tags.go.tpl
Labels: lgtm, approved

#565 Switch ACK to CEL-Based Immutability and Remove Runtime Checks
  pkg/config/field.go
  pkg/model/crd.go
  pkg/model/field.go
  templates/apis/crd.go.tpl
  templates/crossplane/apis/crd.go.tpl
  templates/pkg/resource/sdk.go.tpl
  templates/pkg/resource/sdk_update.go.tpl
Labels: approved

#570 fix documentation templating bug
  templates/apis/crd.go.tpl
Labels: lgtm, approved, ok-to-test
