Repository aws-controllers-k8s/code-generator, pull requests merged in 2025-05, with the labels that each got.

#583 Pin ACK runtime to v0.45.0
  go.mod
  go.sum
Labels: lgtm, approved

#585 Update pkg to v0.0.17
  go.mod
  go.sum
Labels: lgtm

#580 add support for `reconcile-resources` flag
  pkg/generate/ack/release.go
  templates/helm/templates/deployment.yaml.tpl
  templates/helm/values.schema.json
  templates/helm/values.yaml.tpl
Labels: lgtm, approved

#588 Pin ACK runtime to v0.46.1
  go.mod
  go.sum
Labels: lgtm, approved

#590 fix: Use correct CamelCase Kind names in reconcile resources
  pkg/generate/ack/release.go
Labels: lgtm, approved

#591 Ignore .vscode files
  .gitignore
Labels: lgtm, approved

#586 fix: ensure maps of enums are generated properly
  pkg/api/legacy_io_suffix.go
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_sdk.go
Labels: lgtm, approved

#587 docs: modify scripts path
  cmd/ack-generate/README.md
Labels: lgtm, approved, ok-to-test

#594 Add BedRock Agent.MemoryConfiguration.StorageDays to BadDefaultsAssignment
  pkg/apiv2/remove_defaults.go
Labels: lgtm, approved

#595 Allow zero and negative values for generated float32 bounds check
  pkg/generate/code/set_sdk.go
  pkg/generate/code/set_sdk_whitebox_test.go
Labels: lgtm, approved

#596 Add Regex Pattern to documentation
  pkg/api/shape.go
  pkg/apiv2/converter.go
  pkg/model/field.go
  pkg/model/field_test.go
Labels: lgtm, approved
