Repository aws-controllers-k8s/code-generator, pull requests merged in 2025-08, with the labels that each got.

#614 fix(helm): indent of extra volumes
  templates/helm/templates/deployment.yaml.tpl
Labels: lgtm, approved, ok-to-test

#617 Pin ACK runtime to v0.51.0
  go.mod
  go.sum
Labels: lgtm, approved, version/minor

#613 feat: return error on missing required fields during adoption
  pkg/generate/code/set_resource.go
  pkg/generate/code/set_resource_test.go
Labels: lgtm, approved
